// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Proiect_ISP;

import java.util.ArrayList;

public class Angajat extends Persoana {
	
	private Manager manager;
	
	
	public Angajat(String nume, String prenume, String cnp, String email, String parola, Manager manager) {
		super(nume, prenume, cnp, email, parola);
		this.manager = manager;
	}
	
	public Angajat(String nume, String prenume, String cnp, String email, String parola, Manager manager,
			ArrayList<Notificare> listaNotificari, ArrayList<Intalnire> intalniri) {
		super(nume, prenume, cnp, email, parola, listaNotificari, intalniri);
		this.manager = manager;
	}
	
	public Manager getManager() {
		return this.manager;
	}

	@Override
	public String toString() {
		return "Angajat [nume=" + getNume() + ", prenume=" + getPrenume() + ", cnp=" + getCnp() + ", email=" + getEmail() + ", parola="
				+ getParola() + ", listaNotificari=" + listaNotificari + ", intalniri=" + intalniri + "]" + ", manager=" + manager.getNume() + " " + manager.getPrenume();	}
	
	

};
