// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Proiect_ISP;

/************************************************************/
/**
 * 
 */
public enum Departament {

	ResurseUmane,

	ProductionResource,

	MarketingSales,

	AccountingFinance,

	ResearchDevelopment
	;
};
