// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Proiect_ISP;

import java.util.ArrayList;

public class Intalnire {
	
	private String data;

	private String startIntalnire;

	private String stopIntalnire;

	private ArrayList<Persoana> listaParticipanti;

	private Manager responsabil;

	private SalaConferinte sala;

	private String mesaj;
	
	public Intalnire() {
		this.data = null;
		this.startIntalnire = null;
		this.stopIntalnire = null;
		this.listaParticipanti = null;
		this.responsabil = null;
		this.sala = null;
		this.mesaj = null;
	}

	public Intalnire(String data, String startIntalnire, String stopIntalnire, ArrayList<Persoana> listaParticipanti,
			SalaConferinte sala, String mesaj) {
		Notificare notificare = new Notificare(mesaj);
		notificare.setIntalnire(this);
		this.data = data;
		this.startIntalnire = startIntalnire;
		this.stopIntalnire = stopIntalnire;
		this.listaParticipanti = listaParticipanti;
		this.sala = sala;
		this.mesaj = mesaj;
		for(Persoana participant: listaParticipanti) {
			participant.adaugaNotificare(notificare);
		}
	}
	
	public void setResponsabil(Manager manager) {
		this.responsabil = manager;
	}
	
	public void printIntalnire() {
		System.out.println("Data:" + data);
		System.out.println("   Interval: " + startIntalnire + " - " + stopIntalnire);
		System.out.println("   Sala: " + sala.getNumeSala());
		System.out.println("   Mesaj: " + mesaj);
		System.out.println("   Responsabil: " + responsabil.getNume() + " " + responsabil.getPrenume());
		System.out.println("");
	}
	
	public ArrayList<Persoana> getListaParticipanti() {
		return this.listaParticipanti;
	}
	
	public String getData() {
		return this.data;
	}
	
	public void setData(String data) {
		this.data = data;
	}
};
