// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Proiect_ISP;



public class Notificare {
	
	private String mesaj;
	
	private Intalnire intalnire;
	
	
	public Notificare() {
		this.mesaj = "";
	}
	
	public Notificare(String mesaj) {
		this.mesaj = mesaj;
	}
	
	public String getMesaj() {
		return this.mesaj;
	}
	
	public void setMesaj(String mesaj) {
		this.mesaj = mesaj;
	}
	
	public void setIntalnire(Intalnire intalnire) {
		this.intalnire = intalnire;
	}
	
	public void afisareNotificare() {
		this.intalnire.printIntalnire();
	}
};
