// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Proiect_ISP;

import java.util.ArrayList;


public class Persoana {

	private String nume;

	private String prenume;

	private String cnp;

	private String email;

	private String parola;
	
	protected ArrayList<Notificare> listaNotificari;
	
	protected ArrayList<Intalnire> intalniri;

	
	public Persoana() {
		this.nume = "";
		this.prenume = "";
		this.cnp = "";
		this.email = "";
		this.parola = "";
		this.listaNotificari = new ArrayList<Notificare>();
		this.intalniri = new ArrayList<>();
	}
	
	public Persoana(String nume, String prenume, String cnp, String email, String parola) {
		this.nume = nume;
		this.prenume = prenume;
		this.cnp = cnp;
		this.email = email;
		this.parola = parola;
		this.listaNotificari = new ArrayList<Notificare>();
		this.intalniri = new ArrayList<>();
	}
	
	public Persoana(String nume, String prenume, String cnp, String email, String parola,ArrayList<Notificare> listaNotificari, ArrayList<Intalnire> intalniri) {
		this.nume = nume;
		this.prenume = prenume;
		this.cnp = cnp;
		this.email = email;
		this.parola = parola;
		this.listaNotificari = listaNotificari;
		this.intalniri = intalniri;
	}
	
	public String getNume() {
		return this.nume;
	}
	
	public void setNume(String nume) {
		this.nume= nume;
	}
	
	public String getPrenume() {
		return this.prenume;
	}
	
	public void setPrenume(String prenume) {
		this.prenume= prenume;
	}
	
	public String getCnp() {
		return this.cnp;
	}
	
	public void setCnp(String cnp) {
		this.cnp= cnp;
	}
	
	public String getEmail() {
		return this.email;
	}
	
	public void setEmail(String email) {
		this.email= email;
	}
	
	public String getParola() {
		return this.parola;
	}
	
	public void setParola(String parola) {
		this.parola= parola;
	}
	
	public ArrayList<Notificare> getNotificari() {
		return this.listaNotificari;
	}
	
	public ArrayList<Intalnire> getIntalniri() {
		return this.intalniri;
	}
	
	public void adaugaNotificare(Notificare notificare) {
		this.listaNotificari.add(notificare);
	}
	
	public void adaugaIntalnire(Intalnire intalnire) {
		this.intalniri.add(intalnire);
	}
	
	public void stergeIntalnire(Intalnire intalnire) {
		this.intalniri.remove(intalnire);
	}
	
	public void afiseazaNotificari() {
		for(Notificare notificare : this.listaNotificari) {
			notificare.afisareNotificare();
		}
		while(this.listaNotificari.size() != 0) {
			this.listaNotificari.remove(0);
		}
	}
		
	public void afisareIntalniri() {
		if(this.getIntalniri().size() != 0) {
			int counter = 1;
			System.out.println("Ai " + this.getIntalniri().size() + " intalniri in agenda: ");
			for (Intalnire intalnire: this.getIntalniri()) {
				System.out.print(counter + ". ");
				intalnire.printIntalnire();
			}
			System.out.println("");
		} else {
			System.out.println("Nu aveti nici o intalnire in agenda.");
			System.out.println("");
		}
	}
	
	public int getNrNotificari() {
		
		return this.listaNotificari.size();
	}

	@Override
	public String toString() {
		return "Persoana [nume=" + nume + ", prenume=" + prenume + ", cnp=" + cnp + ", email=" + email + ", parola="
				+ parola + ", listaNotificari=" + listaNotificari + ", intalniri=" + intalniri + "]";
	}
	
	

};
